### ISSUE TITLE
Add support for css

### ISSUE THREAD

**Issue by jellehak** [yellow-digital/three-webc#12]
```css
t-material {
  --color: green;
  --metalness:0.5;
}
````

Links
https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle
